name: pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: jetli/wasm-pack-action@v0.3.0
      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: wasm-pack build
      - run: npm install --prefix=www
      - run: npm run build --prefix=www
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: www/dist
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
